### ISSUE TITLE
[Bug] Only one potion can brewed in creative from a full cauldron

### ISSUE THREAD

**Issue by Ahydul** [Sploder12/Potioncraft#2]
When in creative, taking from a full cauldron a potion clicking with a bottle will produce the potion as expected. Repeating this action doesn't create a new potion. 

Whenever you modify the cauldron it gets refreshed. For example, having a full cauldron and taking a potion, then adding a redstone dust and taking another potion would work as expected.

**Comment by Sploder12** [comment]
Thanks for the report!

After looking into it, this behavior is consistent with vanilla Minecraft. For example, taking water out of a cauldron in vanilla will only give you a water bottle if you don't already have one. The reason adding redstone works is that it changes the resulting item NBT which makes it recognized as a different item.
