### ISSUE TITLE
Crash on 1.20.4

### ISSUE THREAD

**Issue by BioMasterZap** [Sploder12/Potioncraft#4]
On Fabric 1.20.4, the 0.3.0 version of this mod (latest for 1.20.4) does not seem to want to launch. I generally see the "Could not execute entrypoint stage 'main' due to errors" crash when the mod isn't compatible with 1.20.4, but Modrinth does list 1.20.1-1.20.4 for v0.3.0 so I thought it was worth sharing.

Crash Log
https://gist.github.com/BioMasterZap/440238a823b93edcd13ca1805f5d4c2d

Log
https://gist.github.com/BioMasterZap/8d3177985c0d66512122b43cbff244c9

**Comment by Sploder12** [comment]
Thank you for the report!

I did not realize that they had changed potion effects so much between the versions. Unfortunately, They didn't fix their bugs so I still have to figure that out. 

I have made release v0.3.1 available on Modrinth and Curseforge with proper support for 1.20.4
